# To enable with eureka client service registry
# spring:
#   application:
#     name: Config-Default    we want the application name as it is.

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
